name: Validation

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ '17.0', '18.0' ]
    paths-ignore:
      - 'hilla-logo.svg'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE/*'
      - 'packages/**/README.md'

jobs:
  init:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate versions.json
        run: | 
          git update-index --chmod=+x ./scripts/generateJsons.sh
          ./scripts/generateJsons.sh

          
